### ISSUE TITLE
Controls addon not working with the 'withVuetifyTheme' decorator

### ISSUE THREAD

**Issue by PaulHellings** [Integrayshaun/vue3-vuetify-storybook-recipe-example#1]
First of all thanks for this recipe, I followed the instructions from this link: https://storybook.js.org/recipes/vuetify.

I noticed there a few improvements possible and will cover the most important one here:

The control add-on is not working when using the decorator. I think the 'binding' is lost somewhere with the render function used in the decorator. I rewrote it with a template string instead, which seems to solve the issue. I only used the v-app component here together with a d-flex div, so structural choices can be made in stories. I'll add a PR with my code.

Note: I am pretty new with storybook, so if I am completely missing something in the original recipe I'd love to hear it ;)

**Comment by ShaunEvening** [comment]
Hey @PaulHellings 👋 

Thank you so much for putting this issue and pull request together 🙏 I really appreciate the effort and enthusiasm :D I'm in the process of moving the examples over to stackBlitz so that people can play with a live example and i'll make sure that your adjustments are credited and ported over <3

**Comment by PaulHellings** [comment]
Awesome, glad I was able to contribute :)
